baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5
disablerss= false
[params]
  # dir name of your blog content (default is `content/posts`)
   contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = true

 
[languages]
  [languages.en]
    title = "nveniz's site"
    subtitle = ""
    
    keywords = ""
    copyright = "© nveniz's site"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"
#    [languages.en.params.logo]
#      logoText = "cd /home/"
#      logoHomeLink = "/"
#     or
#    
#     path = "/img/your-example-logo.svg"
#     alt = "Your example logo alt text"
#
#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"
#      [[languages.en.menu.main]]
#        identifier = "showcase"
#        name = "Showcase"
#        url = "/showcase"



[params.home]
  title = "nveniz's site"
  subtitle = "CS student // Linux enthusiast // Programmer"
  imgPath="/img/pixel-guy-on-pc.png"
  imgAlt="pixel art guy sitting on pc"

[params.footer]
  rss=true
 [[params.social]]
    name = "email"
    url  = "mailto:nveniz01@ucy.ac.cy"
  [[params.social]]
    name = "github"
    url  = "https://github.com/nveniz"
  [[params.social]]
    name = "gpg"
    url  = "/nveniz.pub"

[params.logo]
    logoMark     = "~"
     logoText     = "$ cd /home/"
     logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#ebdbb2"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
     logoCursorPathname = true







[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

 # [[menu.main]]
 #   identifier = "archive"
 #   name       = "Archive"
 #   url        = "/archive"
 #
 # [[menu.main]]
 #   identifier = "random"
 #   name       = "Random"
 #   url        = "/random"
